name: Save Remote Branch

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  firmware_pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Tasmota firmware repo
      uses: actions/checkout@v3
      with:
       repository: arendst/Tasmota-firmware
       path: main
    - name: Add files to commit
      run: |
        # git config --local user.name "My GitHub Actions Bot"
        # git config --local user.email my-github-actions-bot@example.org
        # git switch -c work
    - name: Save firmware in this repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
       commit_message: Tasmota firmware repo backup
       branch: save_firmware
       repository: .
       skip_dirty_check: true
       status_options: '--untracked-files=no'
       push_options: '--force'
       create_branch: true
