name: Save Remote Branch

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  firmware_pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: save_firmware
    - name: Checkout Tasmota firmware repo
      uses: actions/checkout@v3
      with:
       repository: arendst/Tasmota-firmware
       path: main
    - name: Save firmware in this repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
       commit_message: Stubs updated
