name: Save Remote Branch

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  firmware_pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Tasmota firmware repo
      uses: actions/checkout@v3
      with:
       repository: arendst/Tasmota-firmware
       path: main
    - name: Add files to commit
      run: |
        git config --local user.name "Github BUILD"
        git config --local user.email github-actions@github.com
        git switch -c work
        git merge arendst/Tasmota-firmware --allow-unrelated-histories &> status.txt
        echo "$(<status.txt)"
    - name: Save firmware in this repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
       commit_message: Tasmota firmware repo backup
       branch: save_firmware
       status_options: '--untracked-files=no'
       push_options: '--force'
       create_branch: true
